#!/usr/bin/env bash
#
#
# If you choose to run this script to build the project, run:
#
#     $ ./build-and-run
#
#

[[ -z $(which git) ]] && {
	echo "You need git installed. Please run 'xcode-select --install' first."
	echo "Ubuntu: sudo apt install git"
	
	exit 1
}

export BashMatic="${HOME}/.bashmatic"

[[ -s ${BashMatic}/init.sh ]] || {
  rm -rf "${BashMatic}" 2>/dev/null
  git clone https://github.com/kigster/bashmatic "${BashMatic}" 2>&1 1>/dev/null
}

source "${BashMatic}/init.sh"

export ProjectRoot=$(pwd)

header() {
  h1.purple "Project"
  local OIFC=${IFC}
  IFS="|" read -r -a gcc_info <<< "$(gcc --version 2>&1 | tr '\n' '|')"
  export IFC=${OIFC}
  h1 "${bldylw}GCC" "${gcc_info[1]}" "${gcc_info[2]}" "${gcc_info[3]}" "${gcc_info[4]}"
  h1 "${bldylw}GIT:    ${bldblu}$(git --version)"
  h1 "${bldylw}CMAKE:  ${bldblu}$(cmake --version | tr '\n' ' ')"
}

setup() {
  hl.subtle "Creating Build Folder..."
  run "mkdir -p build/run"
  # run "git submodule init && git submodule update"
}

clean() {
  hl.subtle "Cleaning output folders..."
  run 'rm -rf bin/d* include/d* lib/*'
}

build() {
  run "cd build/run"
  run "cmake ../.. "
  run.set-next show-output-on
  run "make -j 12"
  run "make install | egrep -v 'gmock|gtest'"
  run "cd ${ProjectRoot}"
}

tests() {
  if [[ -f bin/divider_tests ]]; then
    run.set-next show-output-on
    run "echo && bin/divider_tests"
  else
    printf "${bldred}Can't find installed executable ${bldylw}bin/divider_tests.${clr}\n"
    exit 2
  fi
}

examples() {
  [[ ! -f bin/radioTelescope ]] && {
    error "You don't have the copiled binary yet".
    exit 3
  }

  run.set-all show-output-on

  hr
  run "bin/radioTelescope"
  hr

}

main() {
  header
  setup
  build
  #tests
  #examples
}

(( $_s_ )) || main
